Expiration
canonical/microcluster pull request #205
Opened 2024-07-26 20:30 UTC by MggMuggins

2024-07-26 20:52 UTC, masnax requested changes
Looks good, there are also 2 more cases to consider:

* Check that a token is not expired at the time we receive it from a joining member.

* If someone tries to create a token with an expired token's name in between it expiring and the next heartbeat, a database record will still exist so the creation will error out with a conflict. We should remove the old record and create a new one instead of failing, especially since a `GET` request will omit expired tokens, which would appear confusing.

2024-07-26 20:52 UTC, masnax commented on internal/rest/resources/heartbeat.go
> +		if token.ExpiryDate.Valid && token.ExpiryDate.Time.Compare(time.Now()) > 0 {
Can you use `token.Expired()` here?

2024-07-26 21:08 UTC, MggMuggins commented
I hadn't marked it ready for review yet :)

This was one of the cases I was concerned about regarding removing expired tokens on heartbeat instead of whenever we touch the tokens table. It makes more sense to me to clean up all the expired tokens when adding a new token rather than trying to special-case it.

2024-07-26 21:28 UTC, masnax commented
I think this doesn't have to be either-or. We can use that helper you added to remove tokens both in the `POST` handler for tokens as well as on heartbeats. I still think we should make sure we don't leave noise in the database that won't be cleaned up until the next time someone wants to grow the cluster.

2024-07-26 21:58 UTC, masnax approved these changes
LGTM, thanks!

2024-07-29 07:39 UTC, roosterfish approved these changes
LGTM, only one comment that can be addressed in a follow up PR.

2024-07-29 07:39 UTC, roosterfish commented on example/test/main.sh
> +  microctl --state-dir "${test_dir}/c1" tokens add default_expiry
Whilst reviewing this part I was wondering if we should add a comment to the microcluster `NewJoinToken()` func telling that by default there is no expiry?

2024-07-29 07:47 UTC, merged