Add dep flags to TICS step
canonical/microcluster pull request #292
Opened 2024-11-19 19:12 UTC by masnax

Addresses the error shown here: https://canonical.tiobe.com/tiobeweb/TICS/AnnotatedSource.html#axes=DeltaDate(1729297017),Date(1731975417),ErrorSuppression(no),CodeType(Set(production,test)),Project(microcluster),Suppressions(no),DiffType(Set(new,unchanged)),File(Path(HIE,microcluster,master,internal,rest,resources,cluster.go))&diff=false&metrics=Annotations(CS)

2024-11-19 19:35 UTC, kadinsayani approved these changes, later dismissed
LGTM - good catch!

2024-11-20 09:08 UTC, roosterfish requested changes

2024-11-20 09:08 UTC, roosterfish commented on .github/workflows/tests.yml
> +    env:
Let's put them under [`env:`](https://github.com/canonical/microcluster/pull/292/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR9) at the root then the vars don't need to be duplicated and are present for all of the jobs.

2024-11-21 19:19 UTC, kadinsayani approved these changes

2024-11-22 07:49 UTC, roosterfish approved these changes

2024-11-22 07:49 UTC, merged