Allow passing additional configuration during bootstrap
canonical/microcluster pull request #72
Opened 2023-11-22 16:51 UTC by markylaing

This PR adds an argument to `(*Microcluster).NewCluster` of the form `map[string]string` which is passed into the `OnBootstrap` hook. This allows clients to pass additional configuration that might be required at bootstrap.

2023-11-22 16:54 UTC, masnax commented
Since we're taking this approach, I suppose we can rip the bandaid off and add a `force` flag to the remove hooks as well.

2023-11-22 17:03 UTC, masnax requested changes
Since not every service using microcluster is going to have MicroCloud's neat and tidy automatic join process, we should probably make this config a more general `InitConfig` and pass it to all of `OnBootstrap`, `PreJoin`, and `PostJoin` so that when going through the join setup, user specified config can get propagated there as well.

2023-11-22 17:03 UTC, markylaing commented
> Since we're taking this approach, I suppose we can rip the bandaid off and add a `force` flag to the remove hooks as well.
> 
> Not necessarily in this PR

We don't necessarily need to take this approach. It's still up for discussion :) That being said, I do think this is better than the alternative, which (I think) seems to require the client to make two api calls, one to bootstrap the microcluster, and the other to initialise ceph... which kind of defeats the purpose of the hooks.

2023-11-22 17:07 UTC, markylaing commented
> Since not every service using microcluster is going to have MicroCloud's neat and tidy automatic join process, we should probably make this config a more general `InitConfig` and pass it to all of `OnBootstrap`, `PreJoin`, and `PostJoin` so that when going through the join setup, user specified config can get propagated there as well.

Yes. Another thought I had was that in it's current form, this PR does the microcluster bootstrap part before the hook is called. This means that any validation of the config that happens server side will be happening too late. Maybe a `PreBootstrap` hook is necessary now?

2023-11-22 17:11 UTC, masnax commented
> > Since not every service using microcluster is going to have MicroCloud's neat and tidy automatic join process, we should probably make this config a more general `InitConfig` and pass it to all of `OnBootstrap`, `PreJoin`, and `PostJoin` so that when going through the join setup, user specified config can get propagated there as well.
> 
> Yes. Another thought I had was that in it's current form, this PR does the microcluster bootstrap part before the hook is called. This means that any validation of the config that happens server side will be happening too late. Maybe a `PreBootstrap` hook is necessary now?

Unlike with `PreJoin` where we actually might have to reconcile information with the existing cluster, there wouldn't be any pre-setup that would have to happen exclusively on the daemon prior to bootstrapping since we won't even have a database or any internal setup, so that would make a `PreBootstrap` hook effectively just a `validateMyConfig` hook, and even then the validation would be limited to sanity checks because we won't have any reference point for what is or isn't a valid config. So I think it's fair to expect the caller to validate the config before sending it through.

2023-11-23 07:40 UTC, UtkarshBhatthere approved these changes
LGTM!

2023-11-23 18:58 UTC, markylaing commented
@masnax I think I've made the changes you've requested.

2023-11-23 22:06 UTC, masnax approved these changes
Looks good, thanks!

2023-11-23 22:06 UTC, merged